* Scripts to import the CSV files into the database
** Create the database
#+begin_src sql :results silent
create database traveling_cost;
#+end_src

** airports.csv
*** Column format:
	| Airport ID            | Unique OpenFlights identifier for this airport.                                     |
	| Name                  | Name of airport. May or may not contain the City name.                              |
	| City                  | Main city served by airport. May be spelled differently from Name.                  |
	| Country               | Country or territory where airport is located. See Countries to cross-reference to ISO 3166-1 codes. |
	| IATA                  | 3-letter IATA code. Null if not assigned/unknown.                                   |
	| ICAO                  | 4-letter ICAO code. Null if not assigned.                                           |
	| Latitude              | Decimal degrees, usually to six significant digits. Negative is South, positive is North. |
	| Longitude             | Decimal degrees, usually to six significant digits. Negative is West, positive is East. |
	| Altitude              | In feet.                                                                            |
	| Timezone              | Hours offset from UTC. Fractional hours are expressed as decimals, eg. India is 5.5. |
	| DST                   | Daylight savings time. One of E (Europe), A (US/Canada), S (South America), O (Australia), Z (New Zealand), N (None) or U (Unknown). See also: Help: Time |
	| Tz database time zone | Timezone in "tz" (Olson) format, eg. "America/Los_Angeles".                         |
	| Type                  | Type of the airport. Value "airport" for air terminals, "station" for train stations, "port" for ferry terminals and "unknown" if not known. In airports.csv, only type=airport is included. |
	| Source                | Source of this data. "OurAirports" for data sourced from OurAirports, "Legacy" for old data not matched to OurAirports (mostly DAFIF), "User" for unverified user contributions. In airports.csv, only source=OurAirports is included. |
   
*** Script
   
#+begin_src sql
use traveling_cost;
create table airports (
    id int not null auto_increment,
    name varchar(255) not null,
    city varchar(255) not null,
    country varchar(255) not null,
    iata varchar(10),                  
    icao varchar(10),                 
    latitude float(53),        
    longitude float(53),       
    altitude integer,              
    timezone decimal(5, 2),              
    dst varchar(3),                    
    tz varchar(255),
    type varchar(255),                 
    source varchar(255),
    primary key (id)
);

load data infile 'csv/airports.csv'
into table airports
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src

** airlines.csv
*** Column format:
	| Airline ID | Unique OpenFlights identifier for this airline.                                      |
	| Name       | Name of the airline.                                                                 |
	| Alias      | Alias of the airline. For example, All Nippon Airways is commonly known as "ANA".    |
	| IATA       | 2-letter IATA code, if available.                                                    |
	| ICAO       | 3-letter ICAO code, if available.                                                    |
	| Callsign   | Airline callsign.                                                                    |
	| Country    | Country or territory where airport is located. See Countries to cross-reference to ISO 3166-1 codes. |
	| Active     | "Y" if the airline is or has until recently been operational, "N" if it is defunct. This field is not reliable: in particular, major airlines that stopped flying long ago, but have not had their IATA code reassigned (eg. Ansett/AN), will incorrectly show as "Y". |

*** Script
#+begin_src sql :results silent
use traveling_cost;
create table airlines (
    id int not null auto_increment,
    name varchar(255) not null,
    alias varchar(128),
    iata varchar(10),     
    icao varchar(10),          
    callsign varchar(255),
    country varchar(255),  
    active varchar(10),
    primary key (id)   
);

load data infile 'csv/airlines.csv'
into table airlines
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src

** routes.csv
*** Column format:
   | Airline                | 2-letter (IATA) or 3-letter (ICAO) code of the airline.                             |
   | Airline ID             | Unique OpenFlights identifier for airline (see Airline).                            |
   | Source airport         | 3-letter (IATA) or 4-letter (ICAO) code of the source airport.                      |
   | Source airport ID      | Unique OpenFlights identifier for source airport (see Airport)                      |
   | Destination airport    | 3-letter (IATA) or 4-letter (ICAO) code of the destination airport.                 |
   | Destination airport ID | Unique OpenFlights identifier for destination airport (see Airport)                 |
   | Codeshare              | "Y" if this flight is a codeshare (that is, not operated by Airline, but another carrier), empty otherwise. |
   | Stops                  | Number of stops on this flight ("0" for direct)                                     |
   | Equipment              | 3-letter codes for plane type(s) generally used on this flight, separated by spaces |

*** Script

#+begin_src sql :results silent
use traveling_cost;
create table routes (
    airline_name varchar(10) not null,    	  
    airline_id int not null,
    src_airport varchar(10) not null,         
    src_airport_id int not null,
    dest_airport varchar(10) not null,
    dest_airport_id int not null,
    codeshare varchar(10),
    stops int,                   
    equipment varchar(128),             
    foreign key (airline_id)
        references airlines(id),
    foreign key (src_airport_id)
        references airports(id),
    foreign key (dest_airport_id)
        references airports(id)
);

set foreign_key_checks=0;
use traveling_cost;
load data infile 'csv/routes.csv'
into table routes
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src

** countries.csv
*** Column format:
   | name       | Full name of the country or territory.                                              |
   | iso_code   | Unique two-letter ISO 3166-1 code for the country or territory.                     |
   | dafif_code | FIPS country codes as used in DAFIF. Obsolete and primarily of historical interested. |

*** Script
#+begin_src sql :results silent
use traveling_cost;
create table countries (
    name varchar(255),
    iso_code varchar(10),
    dafif_code varchar(10),
    primary key (name)
);	

load data infile 'csv/countries.csv'
into table countries
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src
   

** planes.csv
*** Column format:
   | Name      | Full name of the aircraft.                            |
   | IATA code | Unique three-letter IATA identifier for the aircraft. |
   | ICAO code | Unique four-letter ICAO identifier for the aircraft.  |

*** Script

#+begin_src sql :results silent
use traveling_cost;
create table planes (
    name varchar(255),
    iata varchar(10),
    icao varchar(10),
    primary key (name)
);	

load data infile 'csv/planes.csv'
into table planes
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src
   
** cost_of_living_indices.csv
   :PROPERTIES:
   :ORDERED:  t
   :END:
#+begin_src sql :results silent
use traveling_cost;
create table living_cost (
    city varchar(255) not null, 
    country varchar(255) not null,
    slug varchar(128),
    currency varchar(10),
    avg_index decimal(5, 2),
    rent_index decimal(5, 2),
    groceries_index decimal(5, 2),
    restaurant_index decimal(5, 2),
    purchasing_index decimal(5, 2),
	id int not null auto_increment,
	primary key (id)
 );	
#+end_src

#+begin_src sql :results silent
use traveling_cost;
load data infile 'csv/cost_of_living_indices.csv'
into table living_cost
fields terminated by ','
enclosed by '"'       
lines terminated by '\n'
(city,
country,
slug,
currency,
avg_index,
rent_index,
groceries_index,
restaurant_index,
purchasing_index);
#+end_src

** users
   | email         |
   | password_hash |
   | first_name    |
   | last_name     |
   | age           |
   | interests     |
   | history       |

#+begin_src sql
use traveling_cost;
create table users (
email varchar(255) not null check(email like '_%@_%' and	length(email) >= 4),
password_hash varchar(255) not null,
first_name varchar(255),
last_name varchar(255),
age int check (age >= 18),
interests varchar(255),
primary key (email)
);
#+end_src

#+RESULTS:
|---|

#+begin_src sql
use traveling_cost;
create table user_history(
id int not null auto_increment,
email varchar(255) not null,
origin_airport_id int,
destination_airport_id int,
days int,
cost int,	 				 
time_stamp datetime default current_timestamp(),
primary key (id),
foreign key (email) references users(email),
foreign key	(origin_airport_id) references airports(id),
foreign key	(destination_airport_id) references airports(id)
)
#+end_src

#+RESULTS:
|---|

** airline_costs
#+begin_src sql
use traveling_cost;
drop table airline_costs;
create table airline_costs (
	id int not null,
	category int, check (category >= 1 and category <= 5),
	primary key (id),
	foreign key (id) references airlines(id)
);
drop procedure generate_airline_costs;
delimiter $$
create procedure generate_airline_costs()
    begin
        declare i int;
		declare airlines_count int;
        set i = 0;
		set airlines_count = (select count(*) from airlines);
        start transaction;
		delete from airline_costs;
        while i < airlines_count do
            insert into airline_costs (select id, (1 + ceil(rand()*4)) from airlines limit 1 offset i) ;
            set i = i + 1;
        end while;
        commit;
    end$$
delimiter ;

call generate_airline_costs();
#+end_src

#+RESULTS:
|---|

* Views
View user data without exposing the password
#+begin_src sql
create view user_data_view as
select email, first_name, last_name, age, interests
from users;	   
#+end_src

* Distance between airports 
#+begin_src sql
use traveling_cost;
-- drop function distance_between_airports;
delimiter $$
create function distance_between_airports(a int, b int) returns int
begin
return (select ST_Distance_Sphere(
point((select longitude from airports where id = a), (select latitude from airports where id = a)),
point((select longitude from airports where id = b), (select latitude from airports where id = b))			  
)); 
end$$
delimiter ; 
#+end_src	

* Closest airport to point
#+begin_src sql
use traveling_cost;
drop function closest_airport;
delimiter $$

create function closest_airport(p_lat double, p_long double) returns int
deterministic
begin
return (select id
		from airports
		order by ST_Distance_Sphere(
		point(longitude, latitude), 
		point(p_long, p_lat)
		) limit 1);
end$$
delimiter ;  
#+end_src

* Calculate indirect routes and show all details
#+begin_src sql
use traveling_cost;
select 344 into @source;
select 1688 into @destination;
	   
with intermediate as
(select distinct 
		lvl0.src_airport_id as a0,
	    lvl1.src_airport_id as a1,
	    case when (
	     lvl0.dest_airport_id = @destination
	    ) then -1
	    else lvl2.src_airport_id end as a2,
	    case when (
	     lvl0.dest_airport_id = @destination or
	     lvl1.dest_airport_id = @destination
	    ) then -1
	    else lvl2.dest_airport_id end as a3,
	  case
		when lvl0.dest_airport_id = @destination then (
			select distance_between_airports(lvl0.src_airport_id, lvl0.dest_airport_id)
		)
		when lvl1.dest_airport_id = @destination then (
			(select distance_between_airports(lvl0.src_airport_id, lvl0.dest_airport_id)) +
			(select distance_between_airports(lvl1.src_airport_id, lvl1.dest_airport_id))			
		)
		when lvl2.dest_airport_id = @destination then (
			(select distance_between_airports(lvl0.src_airport_id, lvl0.dest_airport_id)) +
			(select distance_between_airports(lvl1.src_airport_id, lvl1.dest_airport_id)) +
			(select distance_between_airports(lvl2.src_airport_id, lvl2.dest_airport_id))
		)
		else 2147483647
	   end as distance
from routes as lvl0
left join routes as lvl1 on lvl0.dest_airport_id = lvl1.src_airport_id
left join routes as lvl2 on lvl1.dest_airport_id = lvl2.src_airport_id
where (lvl0.src_airport_id = @source and lvl0.dest_airport_id = @destination) or
	  (lvl0.src_airport_id = @source and lvl1.dest_airport_id = @destination) or
      (lvl0.src_airport_id = @source and lvl2.dest_airport_id = @destination)
order by distance
limit 20)
select intermediate.distance,
	   a0.city as 'airport0_city', a0.country as 'airport0_country',
	   a1.city as 'airport1_city', a1.country as 'airport1_country', 
	   a2.city as 'airport2_city', a2.country as 'airport2_country', 
	   a3.city as 'airport3_city', a3.country as 'airport3_country',
	   intermediate.a0 as 'airport0_id',
	   intermediate.a1 as 'airport1_id',
	   intermediate.a2 as 'airport2_id',
	   intermediate.a3 as 'airport3_id'
from airports a0, airports a1, airports a2, airports a3, intermediate
where (a0.id =    intermediate.a0 and
		  a1.id = intermediate.a1 and
		  a2.id = intermediate.a2 and
		  a3.id = intermediate.a3);	
#+end_src

* Get airlines data from route
#+begin_src sql
use traveling_cost;
select airlines.name, airlines.icao, airline_costs.category
from routes, airlines, airline_costs
where 
airlines.id = routes.airline_id and
airline_costs.id = routes.airline_id and
routes.src_airport_id=344 and
routes.dest_airport_id=1688;
#+end_src

#+RESULTS:
| name              | icao | category |
|-------------------+------+----------|
| Germanwings       | GWI  |        2 |
| Air Berlin        | BER  |        3 |
| Condor Flugdienst | CFG  |        5 |
| TUIfly            | HLX  |        4 |
| SunExpress        | SXS  |        4 |

