* Scripts to import the CSV files into the database
** Create the database
#+begin_src sql :results silent
create database traveling_cost;
#+end_src

** airports.csv
*** Column format:
	| Airport ID            | Unique OpenFlights identifier for this airport.                                     |
	| Name                  | Name of airport. May or may not contain the City name.                              |
	| City                  | Main city served by airport. May be spelled differently from Name.                  |
	| Country               | Country or territory where airport is located. See Countries to cross-reference to ISO 3166-1 codes. |
	| IATA                  | 3-letter IATA code. Null if not assigned/unknown.                                   |
	| ICAO                  | 4-letter ICAO code. Null if not assigned.                                           |
	| Latitude              | Decimal degrees, usually to six significant digits. Negative is South, positive is North. |
	| Longitude             | Decimal degrees, usually to six significant digits. Negative is West, positive is East. |
	| Altitude              | In feet.                                                                            |
	| Timezone              | Hours offset from UTC. Fractional hours are expressed as decimals, eg. India is 5.5. |
	| DST                   | Daylight savings time. One of E (Europe), A (US/Canada), S (South America), O (Australia), Z (New Zealand), N (None) or U (Unknown). See also: Help: Time |
	| Tz database time zone | Timezone in "tz" (Olson) format, eg. "America/Los_Angeles".                         |
	| Type                  | Type of the airport. Value "airport" for air terminals, "station" for train stations, "port" for ferry terminals and "unknown" if not known. In airports.csv, only type=airport is included. |
	| Source                | Source of this data. "OurAirports" for data sourced from OurAirports, "Legacy" for old data not matched to OurAirports (mostly DAFIF), "User" for unverified user contributions. In airports.csv, only source=OurAirports is included. |
   
*** Script
   
#+begin_src sql
use traveling_cost;
create table airports (
    id int not null auto_increment,
    name varchar(255) not null,
    city varchar(255) not null,
    country varchar(255) not null,
    iata varchar(10),                  
    icao varchar(10),                 
    latitude float(53),        
    longitude float(53),       
    altitude integer,              
    timezone decimal(5, 2),              
    dst varchar(3),                    
    tz varchar(255),
    type varchar(255),                 
    source varchar(255),
    primary key (id)
);

load data infile 'csv/airports.csv'
into table airports
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src

** airlines.csv
   
*** Column format:
	| Airline ID | Unique OpenFlights identifier for this airline.                                      |
	| Name       | Name of the airline.                                                                 |
	| Alias      | Alias of the airline. For example, All Nippon Airways is commonly known as "ANA".    |
	| IATA       | 2-letter IATA code, if available.                                                    |
	| ICAO       | 3-letter ICAO code, if available.                                                    |
	| Callsign   | Airline callsign.                                                                    |
	| Country    | Country or territory where airport is located. See Countries to cross-reference to ISO 3166-1 codes. |
	| Active     | "Y" if the airline is or has until recently been operational, "N" if it is defunct. This field is not reliable: in particular, major airlines that stopped flying long ago, but have not had their IATA code reassigned (eg. Ansett/AN), will incorrectly show as "Y". |

*** Script
#+begin_src sql :results silent
use traveling_cost;
create table airlines (
    id int not null auto_increment,
    name varchar(255) not null,
    alias varchar(128),
    iata varchar(10),     
    icao varchar(10),          
    callsign varchar(255),
    country varchar(255),  
    active varchar(10),
    primary key (id)   
);

load data infile 'csv/airlines.csv'
into table airlines
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src

** routes.csv
*** Column format:
   | Airline                | 2-letter (IATA) or 3-letter (ICAO) code of the airline.                             |
   | Airline ID             | Unique OpenFlights identifier for airline (see Airline).                            |
   | Source airport         | 3-letter (IATA) or 4-letter (ICAO) code of the source airport.                      |
   | Source airport ID      | Unique OpenFlights identifier for source airport (see Airport)                      |
   | Destination airport    | 3-letter (IATA) or 4-letter (ICAO) code of the destination airport.                 |
   | Destination airport ID | Unique OpenFlights identifier for destination airport (see Airport)                 |
   | Codeshare              | "Y" if this flight is a codeshare (that is, not operated by Airline, but another carrier), empty otherwise. |
   | Stops                  | Number of stops on this flight ("0" for direct)                                     |
   | Equipment              | 3-letter codes for plane type(s) generally used on this flight, separated by spaces |

*** Script

#+begin_src sql :results silent
use traveling_cost;
create table routes (
    airline_name varchar(10) not null,    	  
    airline_id int not null,
    src_airport varchar(10) not null,         
    src_airport_id int not null,
    dest_airport varchar(10) not null,
    dest_airport_id int not null,
    codeshare varchar(10),
    stops int,                   
    equipment varchar(128),             
    foreign key (airline_id)
        references airlines(id),
    foreign key (src_airport_id)
        references airports(id),
    foreign key (dest_airport_id)
        references airports(id)
);

set foreign_key_checks=0;
use traveling_cost;
load data infile 'csv/routes.csv'
into table routes
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src

** countries.csv
*** Column format:
   | name       | Full name of the country or territory.                                              |
   | iso_code   | Unique two-letter ISO 3166-1 code for the country or territory.                     |
   | dafif_code | FIPS country codes as used in DAFIF. Obsolete and primarily of historical interested. |

*** Script
#+begin_src sql :results silent
use traveling_cost;
create table countries (
    name varchar(255),
    iso_code varchar(10),
    dafif_code varchar(10),
    primary key (name)
);	

load data infile 'csv/countries.csv'
into table countries
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src
   
** planes.csv
*** Column format:
   | Name      | Full name of the aircraft.                            |
   | IATA code | Unique three-letter IATA identifier for the aircraft. |
   | ICAO code | Unique four-letter ICAO identifier for the aircraft.  |

*** Script

#+begin_src sql :results silent
use traveling_cost;
create table planes (
    name varchar(255),
    iata varchar(10),
    icao varchar(10),
    primary key (name)
);	

load data infile 'csv/planes.csv'
into table planes
fields terminated by ','
enclosed by '"'       
lines terminated by '\n';
#+end_src
   
** cost_of_living_indices.csv
   :PROPERTIES:
   :ORDERED:  t
   :END:
#+begin_src sql :results silent
use traveling_cost;
create table living_cost (
    city varchar(255) not null, 
    country varchar(255) not null,
    slug varchar(128),
    currency varchar(10),
    avg_index decimal(5, 2),
    rent_index decimal(5, 2),
    groceries_index decimal(5, 2),
    restaurant_index decimal(5, 2),
    purchasing_index decimal(5, 2),
	id int not null auto_increment,
	primary key (id)
 );	
#+end_src

#+begin_src sql :results silent
use traveling_cost;
load data infile 'csv/cost_of_living_indices.csv'
into table living_cost
fields terminated by ','
enclosed by '"'       
lines terminated by '\n'
(city,
country,
slug,
currency,
avg_index,
rent_index,
groceries_index,
restaurant_index,
purchasing_index);
#+end_src

** users
   | email         |
   | password_hash |
   | first_name    |
   | last_name     |
   | age           |
   | interests     |
   | history       |

#+begin_src sql
use traveling_cost;
create table users (
email varchar(255) not null check(email like '_%@_%' and	length(email) >= 4),
password_hash varchar(255) not null,
first_name varchar(255),
last_name varchar(255),
age int check (age >= 18),
interests varchar(255),
primary key (email)
);
#+end_src

#+RESULTS:
|---|

#+begin_src sql
use traveling_cost;	
create table user_history(
id int not null auto_increment,
email varchar(255) not null,
origin_city_id int,
destination_city_id int,
days int,
cost int,	 				 
time_stamp datetime default current_timestamp(),
primary key (id),
foreign key (email) references users(email),
foreign key	(origin_city_id) references living_cost(id),
foreign key	(destination_city_id) references living_cost(id)
)
#+end_src

#+RESULTS:
|---|

* Views
View user data without exposing the password
#+begin_src sql
create view user_data_view as
select email, first_name, last_name, age, interests
from users;	   
#+end_src
